convert intro notebook to studio.plot
genjax-community/genjax pull request #1120
Opened 2024-05-23 10:48 UTC by mhuebert

This PR:

- performs the minimal conversion of the intro notebook to gen.studio.plot
- updates each github actions workflow to authenticate with gcloud to we can install the (private) gen-studio dep

2024-05-31 16:21 UTC, sritchie requested changes
1. I think gen-studio should not include a `jaxlib` dependency. JAX wants users to install jaxlib separately depending on GPU vs CPU vs TPU, and the default one is CPU only and will mess with a GPU installation. This dependency is like a "provided" dependency in Java, except Python gives us no way to actually declare one of those...
2. wdyt of making gen-studio an 'extra', vs a main dependency? If someone doesn't want to use it it would be nice to keep the main build slim. They can always do

```python
pip install genjax[studio]
```

to bring studio along for the ride.

2024-05-31 16:21 UTC, sritchie commented on .github/workflows/ci.yml
> +      - id: auth
I wish there was a way to share these across workflows... but I think if you do this credential setting in one job that everyone can share, the effects won't persist into the runtime of the new actions.

@mhuebert is that wrong?

2024-05-31 16:21 UTC, sritchie commented on .github/workflows/pyright.yml
> +      - uses: actions/checkout@v4
get the formatting consistent...

2024-05-31 16:21 UTC, sritchie commented on notebooks/active/intro.ipynb
> +    "key, *sub_keys = jrand.split(key, 10)\n",
love it!

2024-05-31 16:21 UTC, sritchie commented on noxfile.py
> +    session.run(
this was the fix for the initial build errors.

2024-06-03 08:53 UTC, mhuebert commented on .github/workflows/ci.yml
> +      - id: auth
@sritchie I'm not aware of a better way to do this. There are ways of passing data between workflows (see eg. https://stackoverflow.com/questions/67107607/github-actions-pass-data-from-workflow-to-another-workflow) but I don't see how this would let us avoid initializing google auth in each runtime.

2024-06-03 08:55 UTC, mhuebert reviewed
thanks @sritchie for resolving the ci issues!

2024-06-04 15:10 UTC, sritchie approved these changes

2024-06-04 15:10 UTC, merged