First batch of cookbook entries
genjax-community/genjax pull request #1140
Opened 2024-05-28 16:15 UTC by MathieuHuot

This is a first batch of 10 entries for the cookbook in GenJAX.

2024-05-28 16:17 UTC, MathieuHuot commented
Due to a recent PR (I think https://github.com/probcomp/genjax/pull/1122) 2 of the tutorials (mixture, compose) break on a call to `mixture_combinator`. Would be nice to fix before merging but I don't know how to.

2024-05-28 20:55 UTC, femtomc commented
Quick comment: can we consistently call GenJAX — GenJAX, and JAX, JAX

it’s an extremely small thing, but whenever I see someone say GenJax or Jax — it looks sloppy, and it’s not how users standardly refer to JAX

2024-05-29 15:49 UTC, MathieuHuot commented
> Quick comment: can we consistently call GenJAX — GenJAX, and JAX, JAX
> 
> it’s an extremely small thing, but whenever I see someone say GenJax or Jax — it looks sloppy, and it’s not how users standardly refer to JAX

Ok fixed in the code.

2024-06-10 21:37 UTC, sritchie requested changes
Nice work, @MathieuHuot ! Here is a first round of comments. I think we don't have to change much... I'd like to see the linter fixed and formatting changes (pull some of the comments out to markdown), and then I think we should get this deployed. So good!

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/debugging.ipynb
> +   ]
To handle these `ruff` errors, I'd recommend installing the pre-commit hooks... https://genjax.gen.dev/developing.html#commit-hooks if you're in Visual Studio Code, the pylance extension should be showing these as warnings with suggested fixes, yeah?

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/debugging.ipynb
> +   ]
I think all of these need to be moved to `notebooks` (out of `docs/cookbook`), and given entries in `notebooks/_quarto.yml` for them to show up properly in the docs build.

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/debugging.ipynb
> +    "# Running this cell will open a pdb-like interface in the terminal where you can inspect the values of the variables in the scope of the breakpoint.\n",
I would move this to a markdown block below the code block... let's keep code / prose separate, except of course in the case of inline comments explaining some line in the code.

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/debugging.ipynb
> +    "# This jax.debug.print is compatible with all the JAX transformations and higher-order functions like jax.jit, jax.grad, jax.vmap, jax.lax.scan, etc."
same note here as below

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/debugging.ipynb
> +    "# TLDR: use jax.debug.print and jax.debug.breakpoint()\n",
"inside of generative functions, use jax.debug.print and jax.debug.breakpoint() instead of `print()`."

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/generative_fun.ipynb
> +    "from genjax import beta\n",
maybe combine, `from genjax import beta, bernoulli`?

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/generative_fun.ipynb
> +    "# We can now call the generative function with a specified random key\n",
I remain a fan of moving between code and markdown cells vs inlining the comments! I think it will render more clearly.

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/generative_fun.ipynb
> +    "print(tr.args)\n",
I wonder if this is the recommended way. Instead, if we do

```
from genjax import pretty

pretty()  # pretty print the types
```

near the top of the notebook, we should get Penzai printing of everything.

Then if we do a new cell for each these will look nice.

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/generative_fun.ipynb
> +    "# GenJAX functions can be accelerated with JIT\n",
"Using the `@jax.jit` decorator causes the function to compile itself on first call, "accelerating" the function."

Q for @femtomc and @MathieuHuot , and we should note the answer here - does `@jit` commute with `@gen`?

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/methods_of_generative_fun.ipynb
> +    "print(trace.get_sample())\n",
I'd recommend separate cells for these, and use the `pretty()` trick from above so they ecah get their own cell output.

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/methods_of_generative_fun.ipynb
> +    "Then, we can create a choice_map of observations and perform diverse operations on it."
this cell / choicemap note feels like a separate notebook...

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/methods_of_generative_fun.ipynb
> +   "source": [
I think these are all great for the initial cookbook pass and we should get them in, especially since search will expose these on the website.

Down the road I can see splitting up docs for choice maps, traces and then finally the generative function methods.

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# First way of failing\n",
I would split these up and explain what is happening in each. For this one we forgot to tuple:

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# Third way of failing\n",
whoops, `(1)` doesn't make a tuple, we need a comma:

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# Second way of failing\n",
a list ain't a tuple:

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "f.simulate(key, (0.5,)).get_retval()"
woohoo! And @femtomc , btw it really would be nice to auto-tuple...

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# 2] We rely on Tensor Flow Probability and it sometimes does unintuitive things.\n",
Break this heading out of a comment into a markdown cell, maybe with a heading to show that we have a new sharp edge

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "arg = (3.0,)  # 3 is not a valid probability but a valid logit\n",
This is a case where, in strongly-typed land, a "value type" would be great, so you'd have to provide a proper logit object wrapping a float vs a raw float.

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "print(g.assess(chm, (0.5,))[0])  # This should be -inf.\n",
I think you can add an assertion here in the notebook

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# 2] We rely on Tensor Flow Probability and it sometimes does unintuitive things.\n",
can we smooth this over and take what we want to take (probabilities, I think??) here, and pass the logit over to tfp?

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# 4] Going from Python to JAX\n",
nice!!

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "def jax_loop(x):\n",
doesn't seem so tough :)

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# While loops\n",
is `fori_loop` implemented with `while_loop`?

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# 5] Is my thing compiling or is it blocked at traced time?\n",
"trace time"

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# So in order to debug whether a function is running or not, if it passes the first check that Python let's you write it, you can check if it is running by checking if it is traced, before actua
lets vs let's

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# A common TypeError occurs when one tries using np instead of jnp, which is the JAX version of numpy, the former uses 64-bit floats by default, while the JAX version uses 32-bit floats by defau
"when one tries to `import numpy as np` instead of `import jax.numpy as jnp`", maybe

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "innocent_looking_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)\n",
should this be `jnp.array`?

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "    innocent_looking_array = np.array([1, 2, 3], dtype=np.float64)\n",
I thought np.array could do 64 bit?

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/basics/some_oddities.ipynb
> +    "# For instance, in this example, we can de-batch the repeat combinator, which will reduce the memory usage by a factor of 100, at the cost of some performance.\n",
that would be nice if `repeat` had an option for batch size, yeah? @femtomc

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/expressivity/conditionals.ipynb
> +    "    branch_1 = lambda p: 2 * p\n",
Python style is going to want you to write

```python
def branch_1(p):
    return 2 * p
```

2024-06-10 21:37 UTC, sritchie commented on docs/cookbook/expressivity/conditionals.ipynb
> +    "# Similarly to JAX having a custom primitive `jax.lax.cond` that creates a conditional by \"composing\" two functions seen as branches, GenJAX has a custom combinator that \"composes\" two gener
we could also point people to `branch_1.or_else(branch_2)`

2024-06-11 02:46 UTC, MathieuHuot commented on docs/cookbook/basics/debugging.ipynb
> +   ]
ah great, thanks Sam!

2024-06-11 03:18 UTC, MathieuHuot commented on docs/cookbook/basics/some_oddities.ipynb
> +    "    innocent_looking_array = np.array([1, 2, 3], dtype=np.float64)\n",
Sorry the problem is not the line right below the comment. it's using the np.array using float64 in the JAX conditional where the other branch is a jax.numpy with default float32.

2024-06-11 04:11 UTC, MathieuHuot commented on docs/cookbook/expressivity/conditionals.ipynb
> +    "    branch_1 = lambda p: 2 * p\n",
fixed

2024-06-11 04:11 UTC, MathieuHuot commented on docs/cookbook/expressivity/conditionals.ipynb
> +    "# Similarly to JAX having a custom primitive `jax.lax.cond` that creates a conditional by \"composing\" two functions seen as branches, GenJAX has a custom combinator that \"composes\" two gener
added

2024-06-11 04:12 UTC, MathieuHuot commented on docs/cookbook/basics/some_oddities.ipynb
> +    "innocent_looking_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)\n",
no this was on purpose, let me clarify the comment though

2024-06-11 04:14 UTC, MathieuHuot commented on docs/cookbook/basics/debugging.ipynb
> +    "# TLDR: use jax.debug.print and jax.debug.breakpoint()\n",
fixed

2024-06-11 04:15 UTC, MathieuHuot commented on docs/cookbook/basics/debugging.ipynb
> +    "# This jax.debug.print is compatible with all the JAX transformations and higher-order functions like jax.jit, jax.grad, jax.vmap, jax.lax.scan, etc."
ok fixed

2024-06-11 04:16 UTC, MathieuHuot commented on docs/cookbook/basics/debugging.ipynb
> +    "# Running this cell will open a pdb-like interface in the terminal where you can inspect the values of the variables in the scope of the breakpoint.\n",
sg! fixed.

2024-06-11 04:16 UTC, MathieuHuot commented on docs/cookbook/basics/debugging.ipynb
> +   ]
done.

2024-06-11 04:30 UTC, MathieuHuot commented on docs/cookbook/basics/debugging.ipynb
> +   ]
@sritchie  hmmm pre-commit detects some error and won't fix them for me. I get "Found 33 errors.
[*] 20 fixable with the `--fix` option (6 hidden fixes can be enabled with the `--unsafe-fixes` option)." but there doesn't seem to be a  --fix option and rerunning or trying to commit doesn't solve things.

2024-06-17 16:21 UTC, MathieuHuot commented on docs/cookbook/basics/generative_fun.ipynb
> +    "# We can now call the generative function with a specified random key\n",
ok fixed this file.

2024-06-17 16:26 UTC, MathieuHuot commented on docs/cookbook/basics/generative_fun.ipynb
> +    "# GenJAX functions can be accelerated with JIT\n",
@sritchie  No it doesn't, at least not in terms of performance. It's really better to `@jit` at the outer most level that supports `@jit`. Semantically, though, both should be ok in theory, but there's always a possibility for unforeseen bugs.

2024-06-17 16:41 UTC, MathieuHuot commented on docs/cookbook/basics/methods_of_generative_fun.ipynb
> +    "print(trace.get_sample())\n",
ok, it's gonna take a little moment but on it!

2024-06-23 02:59 UTC, sritchie commented
@MathieuHuot let's make a project this week of peeling these off one at a time, getting them reviewed together and getting them merged in... then we can release 0.4.1 by the end of the week, with my `scan` fixes and, if @femtomc is free to help fix the bug that popped up, the new `iterate` and friends.

2024-06-28 13:40 UTC, MathieuHuot commented
> @MathieuHuot let's make a project this week of peeling these off one at a time, getting them reviewed together and getting them merged in... then we can release 0.4.1 by the end of the week, with my `scan` fixes and, if @femtomc is free to help fix the bug that popped up, the new `iterate` and friends.

Sorry @sritchie  this week at PLDI was busy and it was hard to also do other things. I do agree and want to get this merged ASAP and later coobook PRs will just be one at a time. I think this one was special as we changed so much in GenJAX between when I started these entries and the time we started reviewing the PR.

2024-06-30 19:49 UTC, sritchie approved these changes

2024-06-30 19:49 UTC, merged