gen-420 and some type fixes
genjax-community/genjax pull request #1259
Opened 2024-08-05 21:44 UTC by littleredcomputer

cleans up a few type errors and adds a missing else case

2024-08-06 00:10 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +    addr: StaticAddressComponent | EllipsisType = Pytree.static()
Change to `ExtendedStaticAddressComponent` for consistency

2024-08-06 00:10 UTC, femtomc requested changes
Single LoC change otherwise looks great!

2024-08-06 00:11 UTC, femtomc commented on src/genjax/_src/inference/smc.py
> +    q: SampleDistribution = Pytree.field(default=Pytree.const(None))
`None` is officially allowed in JAX, so I think we should restore the `Optional`, and just have `Pytree.field(default=None)`

2024-08-06 16:43 UTC, littleredcomputer commented on src/genjax/_src/inference/smc.py
> +    q: SampleDistribution = Pytree.field(default=Pytree.const(None))
OK. (To make that work, I have changed the definition of `static_check_none`). If you don't think anyone would ever use `Const(None)` then we can remove that method and just check `is None` at the call sites

2024-08-06 16:52 UTC, littleredcomputer commented
I also fixed a problem where smc was defining the instance variable `target`, which was shadowing the method `GenerativeFunction.target()` in an incompatible way (method vs. member). Since nobody was using the method and it was undocumented I deleted it.

2024-08-06 21:43 UTC, littleredcomputer commented
@femtomc ptal

2024-08-10 16:37 UTC, femtomc approved these changes

2024-08-10 16:39 UTC, merged