Remove Sample and Constraint inheritance for ChoiceMap / Selection. Add `edit` & `generate` interfaces. (1/N)
genjax-community/genjax pull request #1322
Opened 2024-09-07 22:56 UTC by femtomc

Then, fix the holes, and define overloads so users don't notice the difference.

TODO:
- [ ] Can we change the signature of mask combinator in a follow up PR?
- [ ] Instead of a type assertion for checking equality between a trace's generative function and self, could we check for tr.get_gen_fn() is self ?

Here are the large scale changes which have occurred:
* `ChoiceMap` no longer inherits from both `Sample` and `Constraint` -- only from `Sample`
* `Selection` inherits from a new type called `Projection`, which is a new concept -- denoting a way to break down a `Sample` into smaller pieces (if allowed for that `Sample`).
* Introduced `ChoiceMapConstraint`, a type to cast a `ChoiceMap` into `Constraint` (in general, old GenJAX users won't really need to care about this type -- as we've added derived interfaces which retain the interfaces where behaviors can be specified just via `ChoiceMap`, without requiring wrapping in `ChoiceMapConstraint`)
* Added 3 new methods to generative functions: `generate`, `project`, and `edit`. `generate` and `project` are actually specializations of `edit`, but we keep them separate to make the implementation more concise and readable -- to avoid introducing extra concepts like `EmptyTrace`. These new methods are used to implement `importance` and `update` -- whose signatures are specialized for people working with generative functions whose sample space is `ChoiceMap`. The `generate`, `project`, and `edit` methods are _more general_ than the derived interfaces -- they are generic over the types `Constraint`, `Projection`, and `EditRequest`. In other words, the old behavior people are used to is retained -- but now as library authors, we can expand the capabilities of the system by adding to the vocabulary of `edit` without disrupting the derived interfaces.
* The interface `update` used to accept an `UpdateProblem` (this was like v0 of `edit`) -- I've restored it to accept as signature `(key, trace, choice_map, argdiffs)`.
* Given the above changes, I've propagated them throughout the code base -- I've focused just on getting things with `ChoiceMap` working with the above changes.
* I've made changes to the tests where signature changes caused errors -- mostly with `update`.

I've added small comments in several of the files to point out specific points of interest. There's a lot of spurious "I had to fix this, because I changed this signature or this type" noise in this PR -- but hopefully my summary above and the comments below allow a concise summarized picture.

2024-09-09 22:03 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
Removed this as unnused -- to focus on choice map constraint compatibility.

2024-09-09 22:03 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
Introduced as a concept to represent the projection of a sample onto a subspace. Of course, with choice map samples -- projections are most conveniently specified via selections.

2024-09-09 22:04 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> +
This PR doesn't introduce `edit` as a method on `EditRequest` (in lines with internal discussion on compositional usage & extension of new `EditRequest` types)

I'll handle that in a follow up PR.

2024-09-09 22:05 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> +
This `IncrementalGenericRequest` represents the edit which corresponds to the old `GenerativeFunction.update` interface.

As you'll see in `GenerativeFunction`, I've kept this method as a derived method on generative functions -- it just defers to the handling of this type of `EditRequest`

2024-09-09 22:15 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> -
I removed several of these types, to focus on just getting support up for `IncrementalGenericRequest` (the type of edit request which implements the old `update` interface move).

2024-09-09 22:16 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> +
These are "cast" types to convert `ChoiceMap` into either the type `Constraint` or the type `Sample`.

2024-09-09 22:16 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> +
This is a "cast" type to convert a `Selection` into a `Projection`.

2024-09-09 22:16 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> -
Leaving `get_choices` for traces that wish to easily furnish `ChoiceMap`, without using the new types.

2024-09-09 22:17 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> +
The `Trace.update` method of course defers its implementation to `GenerativeFunction.update` -- but that further defers its implementation to `GenerativeFunction.edit` (which implements `update` via the `IncrementalGenericRequest` edit request).

2024-09-09 22:18 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
`Trace.project` supports this type overload in `projection` to support people just using `Selection`, instead of the new `Projection` type (which works on more generic `Sample` types).

2024-09-09 22:19 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
Yay -- I was able to eliminate `EmptyTrace` entirely, but had to move logic into a `GenerativeFunction` interface method to do it -- the interface method is `GenerativeFunction.generate` (named after Gen.jl's `generate`) -- this is the general `Constraint` version of `GenerativeFunction.importance` -- `GenerativeFunction.importance` stays and works natively with `ChoiceMap` (again, for those who don't care about `Sample`, `Constraint`, the new types, etc...)

2024-09-09 22:20 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> +    @abstractmethod
This is `generate` -- it's just like `importance`, but it accepts a generic `Constraint` (need not be specialized to `ChoiceMap`).

2024-09-09 22:21 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> -
Now, I've added `importance` and `update` as derived interfaces -- they work natively with choice map (but they rely on `generate` and `edit` internally, which are the more general methods which `GenerativeFunction` implementors actually implement)

2024-09-09 22:21 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> -        raise NotImplementedError
Here is the derived `update` interface -- just defers to a call to `GenerativeFunction.edit` with an `IncrementalGenericRequest`.

2024-09-09 22:22 UTC, femtomc commented on src/genjax/_src/core/interpreters/staging.py
Added some of these staged ("trace and get the return type shape") methods for `generate` and `edit`.

2024-09-09 22:23 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/mask.py
> +        inner_chm = bwd_move.constraint.choice_map
The code here is disgusting -- I just wrote the math above directly into this big long computation for the weight.

2024-09-11 16:56 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
ChoiceMap is a `Sample`, and `Selection` is a `Projection` that operates on `ChoiceMap`.

2024-09-11 16:56 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +
We need only add `ChoiceMapConstraint` to cast a `ChoiceMap` to the `Constraint` type.

2024-09-11 16:57 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +# Copyright 2024 MIT Probabilistic Computing Project
I moved traces and generative functions into this file to avoid cyclic dependencies in imports.

2024-09-11 16:57 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +
This is a new method (not a new name!) -- it's the `Constraint` generic version of `importance`

2024-09-11 16:58 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +
This is `project` -- it lives off generative functions now. Traces defer their implementation of `project` to the logic inside the generative function.

2024-09-11 16:58 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +
`update` is a derived interface -- it's `edit`, provided with an `IncrementalGenericRequest` (todo on naming)

2024-09-11 16:59 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +
`importance` is just `generate` with a `ChoiceMap` provided as the constraint. We then lift it into a `ChoiceMapConstraint` under the hood, and call `generate`.

2024-09-11 17:00 UTC, femtomc commented on src/genjax/_src/core/interpreters/staging.py
>      return get_data_shape(gen_fn.simulate)(key, args)
In this file, I added "trace and get the output shape" methods for both `generate` and `update`.

2024-09-11 17:00 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/dimap.py
> +    ) -> tuple[DimapTrace[R, S], Weight, Retdiff[S], EditRequest]:
Right now we only support `IncrementalGenericRequest` -- that's fine, we'll add more in the future.

2024-09-11 17:01 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/mask.py
This (and elsewhere in the PR!) we are assuming that -- anytime you use an `IncrementalGenericRequest` with `edit`, the backward request (the request that would "put the trace back into its initial state") is also an `IncrementalGenericRequest`

I'd like to figure out a way for us to state these assumptions (and there will be others, for other edit requests) -- but saving for a future PR.

2024-09-11 17:03 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/vmap.py
> -        axis_sizes = jax.tree_util.tree_map(find_axis_size, self.in_axes, args)
This change fixes a deprecation warning emitted by JAX.

2024-09-11 17:04 UTC, femtomc commented on src/genjax/_src/generative_functions/distributions/distribution.py
> -    def importance_choice_map(
In several other places in this PR, I essentially replace the underlying logic of `importance` as a specialization of `edit` ... with `generate`.

This is nice -- because it cleans up the signature & implementor concerns.

Also! It lets us kill `EmptyTrace` entirely.

2024-09-11 17:05 UTC, femtomc commented on src/genjax/_src/generative_functions/distributions/distribution.py
>              case _:
We're still just raising trace time exceptions in this PR -- not doing anything fancy with typing.

2024-09-11 17:06 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +    ) -> tuple[Trace[R], Weight, Retdiff[R], Constraint]:
Also note here how the signature of `update` changes -- doesn't involve `EditRequest` at all.

2024-09-11 17:07 UTC, femtomc commented on tests/core/generative/test_core.py
>          tr = f.simulate(jax.random.PRNGKey(0), ())
@sritchie In general, it's a bad idea to assert comparisons with raw numbers... our code is stochastic, so even an internal change to how the random seeds work in JAX could then break out tests.

2024-09-11 17:08 UTC, femtomc commented on tests/generative_functions/test_distributions.py
> -            MaskedConstraint(True, C.v(1.0)),
I removed `MaskedConstraint` entirely -- in favor of just getting everything working with `ChoiceMap` (and the constraint wrapper `ChoiceMapConstraint`)

2024-09-11 17:11 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +
Later on, we'll also add `regenerate` (it's an `edit`, provided with an `IncrementalRegenerateRequest` -- using `Projection` to pick which random variables to re-propose)

2024-09-12 16:48 UTC, sritchie requested changes

2024-09-12 16:48 UTC, sritchie commented on notebooks/cookbook/expressivity/dynamic_computation.ipynb
> +    "    constraints = genjax.ChoiceMapConstraint(C.n())\n",
thinking out loud about `.to_constraint()` on ChoiceMap... I appreciate that the type system will tell people if they get these things wrong

2024-09-12 16:48 UTC, sritchie commented on notebooks/cookbook/inference/mcmc.ipynb
> +    "    # The update method takes a random key, a trace, and a IncrementalGenericRequest object.\n",
we should update this comment, because that's not in fact what we're passing, we're just passing argdiffs.

2024-09-12 16:48 UTC, sritchie commented on notebooks/cookbook/inference/mcmc.ipynb
> +    "    # The update method takes a random key, a trace, and a IncrementalGenericRequest object.\n",
AND the fwd_choices?

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
This is not a pipe

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
> +    def complement(self) -> "Selection":
why add this one vs forcing ~? It's fine of course, but want to add a test that these are the same? Can't let me coverage go down

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
> +        return self.filter(sample)
test please! we can add to the existing tests and show that these are the same. Perfect generative test...

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
> +        return self.filter(sample)
For when we have those

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
> +
not cast, just wrap, yeah?

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
> +class ChoiceMapConstraint(Constraint, ChoiceMap):
I still wonder if we can make this NOT a choicemap anymore, and force users to go get the choice_map out. that would make me happier

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/generative_function.py
> +    ) -> tuple[Trace[R], Weight, Retdiff[R], Constraint]:
when I think of a good name for this returned object we're making a proper class vs a tuple

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/generative_function.py
> +        return sample, score, retval
oopsies, test please?

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/generative_function.py
> +    def edit(
here we goooo

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/generative/core.py
> +from genjax._src.core.interpreters.staging import Flag
is there now a better name than `core` for this file?

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/interpreters/staging.py
> +def get_importance_shape(gen_fn, choice_map, args):
add types please (input and output)

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/core/interpreters/staging.py
> +def get_edit_shape(gen_fn, tr, problem):
missing types

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/mask.py
> +    def get_args(self) -> tuple[Any, ...]:
whoops, put Flag back as the first element

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/mask.py
> +    def get_args(self) -> tuple[Any, ...]:
I think this should return a 2-tuple.

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/mask.py
> +        inner_chm_sample = self.inner.get_sample()
just call get_choices() here for now?

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/mask.py
> +        sample: Sample,
for now, imo we should keep this as ChoiceMap.

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/scan.py
>              lambda idx, subtrace: ChoiceMap.entry(subtrace.get_sample(), idx),
I think this is busted, the sample is going to be wrapped in a `ChoiceMap.value` if it's not a `ChoiceMap`, not what we want, right? with `Sample` having no structure I don't think there is a way to implement this for general samples.

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/scan.py
>              submap = constraint.get_submap(idx)
this is where I want you to pull out the choicemap and call `get_submap` on it, vs having `ChoiceMapConstraint` be a ChoiceMap (breaking our current algebraic data type status!!)

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/scan.py
> +            assert isinstance(submap, ChoiceMapConstraint)
no need for this assertion if you get the choicemap out yourself and call get_submap

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/switch.py
> +            masked_submap = _chm.mask(jnp.all(_idx == idx))
take away the `jnp.all`; then if you DO have a concrete idx, not a jnp.array(idx), you can optimize away a bunch of the choicemap structure.

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/switch.py
>          subsamples = list(map(lambda v: v.get_sample(), self.subtraces))
just call `get_choices()`, the assertion shows that this is all we support for now.

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/switch.py
> +            retval_leaves.append(retval_leaf)
gnarly

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/switch.py
> +        retvals = list(
do you need these list wrappers?

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/switch.py
> +        branch_functions = list(map(edit_dispatch, range(len(self.branches))))
my eyes are glazing over, tapping @littleredcomputer in for careful reading

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/vmap.py
> +    def get_sample(self) -> ChoiceMap:
how does this pass typechecking? also, call `get_choices() as this is busted and will wrap a non-choicemap sample in `ChoiceMap.value`

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/distributions/distribution.py
>      def get_sample(self) -> ChoiceMap:
call get_choices?

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/distributions/distribution.py
> -    def importance_choice_map(
Nice!!

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/distributions/distribution.py
> +        )  # pyright: ignore
woah buddy what's this ignore about??

2024-09-12 16:48 UTC, sritchie commented on src/genjax/_src/generative_functions/distributions/distribution.py
> +        sample: Sample,
re-add ChoiceMap

2024-09-12 16:48 UTC, sritchie commented on tests/core/generative/test_core.py
>          tr = f.simulate(jax.random.PRNGKey(0), ())
thanks for fixing

2024-09-12 16:48 UTC, sritchie commented on tests/core/test_staging.py
> +        assert isinstance(bwd_request, Chm)
great character savings

2024-09-12 16:48 UTC, sritchie commented on tests/generative_functions/test_distributions.py
> -            MaskedConstraint(True, C.v(1.0)),
`.mask(True)`  is a no-op, this won't do anything (since we know `True` concretely)

2024-09-12 16:48 UTC, sritchie commented on tests/generative_functions/test_distributions.py
> +            C.v(1.0).mask(False),
This is equal to `C.n()`, masking to concrete false returns `ChoiceMap.empty()`

2024-09-12 16:48 UTC, sritchie commented on tests/generative_functions/test_distributions.py
> +            C.v(1.0).mask(True),
no-op

2024-09-12 16:48 UTC, sritchie commented on tests/generative_functions/test_mask_combinator.py
> +        assert w == 0.0
this is the old test, please re-add the one we wrote with @MathieuHuot

2024-09-12 16:56 UTC, femtomc commented on tests/generative_functions/test_mask_combinator.py
> +        assert w == 0.0
wait -- I kept both tests from main and my branch...

did i clobber something?

2024-09-12 17:00 UTC, femtomc commented on notebooks/cookbook/expressivity/dynamic_computation.ipynb
> +    "    constraints = genjax.ChoiceMapConstraint(C.n())\n",
As of this PR, people using the old interfaces don't have to worry about doing this, it only occurs here because Mathieu explicitly used the new interface -- but could be beneficial as we build towards the future.

2024-09-12 17:05 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +class ChoiceMapConstraint(Constraint, ChoiceMap):
it's not users who suffer from this choice, it's us -- in our internal implementation of generative functions -- you'd then need to (a) unwrap the ChoiceMapConstraint -- (b) call `get_submap` on the inside choice map and (c) wrap it back up.

2024-09-12 17:05 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +class ChoiceMapConstraint(Constraint, ChoiceMap):
But that sounds like it could perfectly fit in `get_submap`...

2024-09-12 17:06 UTC, femtomc commented on src/genjax/_src/core/interpreters/staging.py
> +def get_edit_shape(gen_fn, tr, problem):
we can't add types here, even with `TYPE_CHECKING`, because then `beartype` will complain about forward references.

2024-09-12 17:06 UTC, femtomc commented on src/genjax/_src/core/interpreters/staging.py
> +def get_importance_shape(gen_fn, choice_map, args):
we can't add types here, even with TYPE_CHECKING, because then beartype will complain about forward references.

2024-09-12 17:07 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/mask.py
> +        inner_chm_sample = self.inner.get_sample()
Is the suggestion here to remove `get_sample`? I'm fine to do that for now, if that's what you mean

2024-09-12 17:09 UTC, femtomc commented on tests/generative_functions/test_distributions.py
> -            MaskedConstraint(True, C.v(1.0)),
Is the correct thing `.mask(Flag(True))`? or `.mask(jnp.array(True))`?

2024-09-12 17:34 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
missed joke -- or explain further if you want changes

2024-09-12 17:37 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> +from genjax._src.core.interpreters.staging import Flag
concepts?

2024-09-12 17:38 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/mask.py
> +    def get_args(self) -> tuple[Any, ...]:
Can we change the signature of mask combinator in a follow up PR?

2024-09-12 17:41 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/scan.py
>              lambda idx, subtrace: ChoiceMap.entry(subtrace.get_sample(), idx),
not until we make choice map a generic collection ... fixing now

2024-09-12 17:44 UTC, femtomc commented on src/genjax/_src/generative_functions/distributions/distribution.py
> +        )  # pyright: ignore
can remove now -- had to add when we had all the `Flag` stuff

2024-09-12 17:47 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +    def complement(self) -> "Selection":
Do you mean -- why not force ~ in projection? versus naming the method `Projection.complement`?

2024-09-12 17:47 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +class ChoiceMapConstraint(Constraint, ChoiceMap):
I see now that you're upset about the assertions

2024-09-12 18:12 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +        return self.filter(sample)
renamed `Projection.project` to `Projection.filter` -- therefore, only "redundant" method on `Selection` is `Selection.complement` -- which I can add a test for coverage to resolve this conversation.

2024-09-12 18:13 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +    ) -> tuple[Trace[R], Weight, Retdiff[R], Constraint]:
now you're doing real PL research work

2024-09-12 18:14 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +class ChoiceMapConstraint(Constraint, ChoiceMap):
@sritchie How about this -- remove `ChoiceMap` inheritance on `ChoiceMapConstraint`, add `to_constraint` to `ChoiceMap` -- do the unpacking, remove the asserts.

2024-09-12 18:16 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/switch.py
> +        branch_functions = list(map(edit_dispatch, range(len(self.branches))))
switch is possibly the most impenetrable part of the codebase -- i'd recommend we dissect in a separate PR.

2024-09-12 18:28 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> +
This is handled in #1337.

2024-09-12 19:11 UTC, sritchie commented on tests/generative_functions/test_mask_combinator.py
> +        assert w == 0.0
oh cool I saw this and didn't see the other, sounds good if they're both there

2024-09-12 19:18 UTC, sritchie commented on tests/generative_functions/test_distributions.py
> -            MaskedConstraint(True, C.v(1.0)),
no it's good, just remove it (it's concretely true so there's no reason to call `.mask(True)`.

2024-09-12 19:33 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
![image](https://github.com/user-attachments/assets/9c6c0190-bf9f-4ef5-bc89-011f70b845b4)

2024-09-12 19:34 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
> +    def complement(self) -> "Selection":
I meant that we can already call `~` on a selection, so why do we need to add a `.complement(..)` method, since I don't see it used anywhere (could be wrong)

2024-09-12 21:00 UTC, femtomc commented on tests/generative_functions/test_distributions.py
> -            MaskedConstraint(True, C.v(1.0)),
Well I want to test the code paths where it’s not concretely true or concretely false

2024-09-12 21:00 UTC, femtomc commented on notebooks/cookbook/inference/mcmc.ipynb
> +    "    # The update method takes a random key, a trace, and a IncrementalGenericRequest object.\n",
Changed the comment to reflect this.

2024-09-12 21:02 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +    def complement(self) -> "Selection":
It’s part of the specification for a Projection — for Projection, one needs to specify a partitioning of the sample space, and that’s what complement is there for

2024-09-12 21:02 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +    def complement(self) -> "Selection":
We could remove complement as the name of the method and just assert that subtypes must implement the ~ dunder?

2024-09-12 21:04 UTC, femtomc commented on tests/generative_functions/test_distributions.py
> -            MaskedConstraint(True, C.v(1.0)),
I added jnp.array(…) versions of these lines — hopefully this hits the not concrete code (must check)

2024-09-12 22:01 UTC, sritchie commented on tests/generative_functions/test_distributions.py
> -            MaskedConstraint(True, C.v(1.0)),
yup that will hit it!

2024-09-13 02:59 UTC, littleredcomputer submitted a review, later dismissed
I like it.

2024-09-13 02:59 UTC, littleredcomputer commented on notebooks/cookbook/expressivity/dynamic_computation.ipynb
> +    "    update_problem = genjax.IncrementalGenericRequest(arg_diff, constraints)\n",
Suppose I have never heard of argdiffs and don't care. Is there a one-step class I can use to just use update to get the weight of a change to traced values and nothing else?

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
I would say that a ChoiceMapConstraint both "is-a" ChoiceMap (inheritance) and "has-a" ChoiceMap (composition) so I'd say pick one. The implementation of the choice map interface would naturally be delegated to the member variable, so just expose it as a method

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
In Golang, if you mention a struct namelessly in another struct's definition, you get all the member variables and methods of the included struct in the hosting struct for free, which appears to be what we want here, so you're not alone in wanting this pattern: this is supposed to be an enriched choice map. But it's not enriched by having any additional data, it's enriched in what way? I'm not opposed to using inheritance for this

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
If _any_ choice map can serve as a constraint, why did we remove Constraint from ChoiceMap's subtypes? It still leaves open the possibility of a Constraint that is _not_ a ChoiceMap which I understand is desirable.

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
I'm more convinced than ever. Please consider putting Constraint back in to the base classes of ChoiceMap. If there are methods of ChoiceMap that _every constraint should satisfy_ then make those methods of Constraint.  Then, those functions that can do their job on any constraint, whether or not it's a choice map, can delcare the parameter of that type.

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/core.py
> +
<img width="459" alt="Screenshot 2024-09-12 at 15 59 38" src="https://github.com/user-attachments/assets/727160b9-11a7-439d-b6c9-463c045ff472">

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/core.py
> +class IncrementalGenericRequest(EditRequest):
IIUC, "Incremental" means "I want to tamper with the arguments, creating the possibility that you will have to re-execute parts of the model" and "Generic" means "I want to change the values of traced variables with a ChoiceMap." The name isn't wrong, but conveys little to the neophyte. Everything else seems dumb, though, like "ChoiceMapWithArgDiffs", which is less appetizing.

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/generative_function.py
> +
If we agree that ChoiceMap is-a Constraint, then the signatures of `importance` and `generate` are the same (and I suspect the implementation is as well).

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/generative_function.py
> +
I understand how `regenerate` compares to `importance`:  with importance, I have cooked up some new values and want to measure a weight. For regenerate, I want to _indicate_ a subset of variables, roll the dice again, and get the weight as if I had asked for importance with those values.

But does it make sense to also allow argdiffs? I would think that, argdiffs could cause different branches to be taken in the model, so the Projection would have to account for that. Maybe so. At any rate, using the original projection on the returned trace should reveal exactly those values which were recomputed?

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/generative_function.py
> +                    maybe_kwarged_gen_fn = self.get_gen_fn_with_kwargs()
should we kwarg gen fns when we create them if `self.kwargs` ?

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/core/generative/generative_function.py
> +                    maybe_kwarged_gen_fn = self.get_gen_fn_with_kwargs()
I'm wondering if there's a way to sweep this under the rug

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/mask.py
Random thought: what if the backward request were a thunk? Just return `lambda tr: whatever it takes` and then there's no type

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/scan.py
> +            assert isinstance(submap, ChoiceMapConstraint)
A ChoiceMap is a kind of Constraint. Simple as. Not every Constraint will allow `get_submap`, so we need a ChoiceMap here, and we have one. Which is nice!

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/scan.py
> +            w = _inner_project(key, subtrace, subprojection)
I'd just inline the body of _inner_project here, it's easier to read that way

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/switch.py
> +
```suggestion
branch_functions = [lambda sample, args: self._assess(k, sample, args) for k in range(len(self.branches))]
```

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/switch.py
> +                lambda x: jtu.tree_unflatten(retval_defs[x], retval_leaves[x]),
A comment in this function would be handy since it's not obvious why we're unflattening things

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/switch.py
> +        retvals = list(
If you do, a list comprehension is preferred here

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/switch.py
>              key = jax.random.PRNGKey(0)
Since key is constant, these computations feel pro-forma. Can these shapes change from one invocation of _empty_edit_defs to the next? Could these shapes be computed once and then saved?  If we stop using penzai for data classing, these objects are not necessarily frozen and so some precomputation could be done. However trace is a parameter, leaving me to wonder how the results are sensitive to the trace. 

Whenever we resort to tree_flatten and tree_unflatten, it would be cool to have a comment explaining why this is necessary.

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/switch.py
>              key = jax.random.PRNGKey(0)
This would be less gnarly if we had a function that would do the job for one branch, and have the for loop drive that function

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/vmap.py
> +            assert isinstance(subconstraint, ChoiceMapConstraint), type(subconstraint)
Granting that there are other kinds of constraints beside ChoiceMapConstraints, can't we just agree that the ChoiceMap is a model for every constraint, so that we can avoid this kerfuffle? Concretely: it doesn't seem awful to require that every constraint be callable with an address segment even if it has no substructure (it may raise an exception in that case)

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/vmap.py
> +            assert isinstance(subconstraint, ChoiceMapConstraint), type(subconstraint)
Like ValueChm, which is an _equality constraint_. It has get_submap which always returns empty.

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/combinators/vmap.py
> +    ) -> tuple[VmapTrace[R], Weight, Retdiff[R], EditRequest]:
I'm glad that GFs and not Traces own these implementations. One feature of the trace API is that you can call update on it and it supplies self.get_gen_fn() for the GF. Instead of a type assertion, could we check for `tr.get_gen_fn() is self `? And if not, emit the error message "you must supply a trace generated by _this_ generative function in order to use this interface"?

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/static.py
> +        self.key, sub_key = jax.random.split(self.key)
Yikes! Do we really want this object to acquire time-varying state in this way?

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/static.py
> +    score: Score = Pytree.field(default_factory=lambda: jnp.zeros(()))
since numpy arrays are immutable, I do not think we need a factory here, just a default value

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/static.py
> +        self.key, sub_key = jax.random.split(self.key)
...well, it's a handler object, so probably only used once and then thrown away... or is it? Maybe I am confusing generate and regenerate. Is the idea to produce a stream of values?

2024-09-13 02:59 UTC, littleredcomputer commented on src/genjax/_src/generative_functions/static.py
> +        self.key, sub_key = jax.random.split(self.key)
...if we really want this, it would be way more efficient as a scan over keys, than one at a time, though you would have to say up front how many you wanted

This transform seems un-JAXy

2024-09-13 10:07 UTC, femtomc commented on notebooks/cookbook/expressivity/dynamic_computation.ipynb
> +    "    update_problem = genjax.IncrementalGenericRequest(arg_diff, constraints)\n",
We define a convenient way to do this via Trace.update (just accepts a key, a choice map, and optionally — argdiffs)

2024-09-13 10:15 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
Unfortunately not any choice map can serve as a constraint — we have to think forwards to using choice map as a generic container, which may contain EditRequest (!) values at its addresses (this is not a bridge too far, it’s going to be a perfectly consistent thing that people will want to do when we unlock the edit functionality)

I started by removing Sample and Constraint with this in mind … is a Constraint a Sample? Well, sometimes yes — but sometimes no. If I use a Constraint type inside my ChoiceMap which says “constrain the generation to be within some range on the reals” — that’s not a sample, that constraint doesn’t correspond to a value that the generative function may actually sample at that address, it’s asking for the sample to satisfy some property.

and then we go up the hierarchy … what if we have an EditRequest at an address — asking a callee of the toplevel generative function to modify its subtrace in some way? Well, that’s not a constraint (doesn’t have to be — c.f. discussion about regenerate for an example of how an edit request need not contain a constraint)

For exposing the way that things used to work (backwards compatibility), there’s no cost to adding an enriched type like ChoiceMapConstraint (or, in the future, ChoiceMapEditRequest) — and based on some of my reasoning in this discussion, I think it is better to not try and pile everything into choice map … but to eventually move towards choice map as a generic collection type.

2024-09-13 10:18 UTC, femtomc commented on src/genjax/_src/core/generative/core.py
> +class IncrementalGenericRequest(EditRequest):
The name is not good, and I change it in #1337

2024-09-13 10:19 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +                    maybe_kwarged_gen_fn = self.get_gen_fn_with_kwargs()
I quickly put together the kwargs functionality when I contributed it — I’m happy to work on another PR with you that really understands the design

2024-09-13 10:23 UTC, femtomc commented on src/genjax/_src/generative_functions/static.py
> +        self.key, sub_key = jax.random.split(self.key)
It’s used once and then thrown away, and we can’t setup a scan because user code which consumes the keys in static gen fns is heterogeneous in computation shape.

2024-09-13 10:24 UTC, femtomc commented on src/genjax/_src/generative_functions/static.py
> +        self.key, sub_key = jax.random.split(self.key)
This will make more sense after we discuss staged JAX interpreters next week.

2024-09-13 16:03 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/mask.py
like the type is a `Callable`?

2024-09-13 16:04 UTC, femtomc commented on notebooks/cookbook/expressivity/dynamic_computation.ipynb
> +    "    update_problem = genjax.IncrementalGenericRequest(arg_diff, constraints)\n",
The syntax is `Trace.update(key, chm)`

2024-09-13 16:10 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
@littleredcomputer a simple (trivial) example of this -- not relevant to this PR, but relevant to a (soon to be incoming) PR:

```python
def outer_model(v):
    return inner.scan(n=20)(v, None) @ "inner"
```

Say you want to update a specific index in the scan via an `IndexEditRequest` (denoting a specialized update -- which only looks at the specified index of the scan) -- you need some way to create an `EditRequest` which _addresses_ the inner scan.

So the natural way to do that would be to say:
```
ChoiceMapEditRequest(ChoiceMap.kw("inner" = IndexEditRequest(5, ...))
```

This is what I mean when I say "we should be moving towards a world where `ChoiceMap` is more like a generic collection type"

We may not have to fully embrace that world, but it's going to be very natural to want to do things like the above.

2024-09-13 16:26 UTC, littleredcomputer commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
... and that's a Constraint, right? To win this game, you must produce a counterexample: a ChoiceMap which is not a constraint.

My position is, that since the implementation of `Constraint` is `pass`, any object can be a constraint, merely by mentioning its name among its base classes and changing nothing else--certainly every ChoiceMap can be a Constraint too. For the example you supply, it's a Constraint, like any other object.

If you are planning to add a method to Constraint which a ChoiceMap cannot satisfy, even in principle, please name it.

I think you're saying "it's possible to build a ChoiceMap which is inappropriate for use in some contexts where Constraint is required," or "the description Constraint is not appropriate for certain ChoiceMaps". If either of those is true, and you want to enforce this discipline at the type level, you are going to have to say something about what a Constraint _is_. 

As it stands, the class of ChoiceMaps is a subclass of Constraint. Admit that, and all the assertions go away.

2024-09-13 16:28 UTC, littleredcomputer commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
The fact that there are Constraints that are not ChoiceMaps--such as an inequality of a continuous variable--is arguing the opposite direction, which I agree with.

2024-09-13 16:49 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
```ChoiceMapEditRequest(ChoiceMap.kw("inner" = IndexEditRequest(5, ...))```
is not a `Constraint`

2024-09-13 16:53 UTC, femtomc commented on src/genjax/_src/core/generative/choice_map.py
> +    choice_map: ChoiceMap
We don't want to confuse `Constraint` and `EditRequest` in the signature of our interfaces -- or in the logic.

We continue to have these conversations about "what the type has to satisfy" -- but we keep forgetting that we're essentially doing something which amounts to something like concepts in C++20 -- combined with template metaprogramming...

In other words, in our library, a type can correspond _to specialized forms of code generation_ -- not just its usage or interfaces. That's essentially what we use the type `Constraint` and the type `EditRequest` now -- they don't have interfaces, they denote extendable customized code generation paths which denote particular types of things (in the case of `Constraint` -- specialized codegen for importance sampling for generative functions -- in the case of `EditRequest` -- specialized codegen for SMC moves to move from trace to trace)

Is this reasoning satisfactory? We haven't talked about this clearly -- but this is the clear reason why we have `pass` types like `Constraint` and `EditRequest` -- they're specialized branches in our compiler for different types of inference logic.

We separate them at the type level because they correspond to code generation for inference logic _with different mathematical requirements / guarantees_

2024-09-13 17:03 UTC, femtomc commented on src/genjax/_src/core/generative/generative_function.py
> +
Argdiffs are required -- exactly because of the example you're thinking about: say we regenerate a random choice which is an index for a switch -- the `edit` interface for `IncrementalRegenerateRequest` has to account for this, so when we visit the switch, we need to know that we changed the branch.

The projection doesn't need to provide further information about what happens when you do this (it only needs a way to provide a subprojection -- for any branch of the switch which we go into) -- but switch itself (if it implements the `IncrementalRegenerateRequest` move) needs to provide a way to sample new values for the switched-to branch.

2024-09-13 17:09 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/mask.py
@littleredcomputer a few more intuitions: the “bwd request” is not just there to reset the trace data — it represents the entire SMC move which puts the trace back.

so, in the signature of the `Callable` -- you'd need to essentially duplicate the signature of `edit` (because the bwd move needs to account for the weight, the retdiff, and then the bwd bwd move ...)

_it may be possible to make this compositional_ -- but it seems more complicated than our current setup

2024-09-13 17:12 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/vmap.py
> +    ) -> tuple[VmapTrace[R], Weight, Retdiff[R], EditRequest]:
That's a good idea.

2024-09-16 12:30 UTC, sritchie reviewed
Boom, just a few follow-up comments

2024-09-16 12:30 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
> +    def complement(self) -> "Selection":
no, that's fine, I didn't realize it was on projection.

2024-09-16 12:30 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
> +class ChoiceMapConstraint(Constraint, ChoiceMap):
I defer to @littleredcomputer and you here as you're discussing this in other comments.

2024-09-16 12:30 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/mask.py
> +    def get_args(self) -> tuple[Any, ...]:
yes, can you leave a TODO in your PR description reminding us?

2024-09-16 12:30 UTC, sritchie commented on src/genjax/_src/generative_functions/combinators/switch.py
> +            masked_submap = _chm.mask(jnp.all(_idx == idx))
Ping on this, cc @littleredcomputer for viz and in case I'm wrong here

2024-09-17 21:41 UTC, femtomc commented on src/genjax/_src/generative_functions/static.py
> +    score: Score = Pytree.field(default_factory=lambda: jnp.zeros(()))
turns out we actually need this or else XLA yells at us:
```python
ValueError: mutable default <class 'jaxlib.xla_extension.ArrayImpl'> for field score is not allowed: use default_factory
```

2024-09-17 21:48 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/vmap.py
> +    ) -> tuple[VmapTrace[R], Weight, Retdiff[R], EditRequest]:
I've pulled this into a TODO for a next PR, okay?

2024-09-17 21:49 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/switch.py
>              key = jax.random.PRNGKey(0)
I'm not yet convinced that this implementation of switch is the way to go -- versus a programmatically simpler (but perhaps, less optimized) one which just uses MaskCombinator (and perhaps composes it with DimapCombinator).

2024-09-17 21:50 UTC, femtomc commented on src/genjax/_src/generative_functions/combinators/switch.py
>              key = jax.random.PRNGKey(0)
> Whenever we resort to tree_flatten and tree_unflatten, it would be cool to have a comment explaining why this is necessary.

This is very hard to explain in a way which will be clear -- sometimes you want to return Pytrees with different "static parts" but the same "dynamic parts" from a jax.lax.cond -- that's why all this annoying stuff is happening here.

2024-09-18 20:39 UTC, sritchie approved these changes

2024-09-18 20:46 UTC, merged

2024-09-18 20:54 UTC, femtomc commented
LOVE IT