Add slicing support to ChoiceMap and ChoiceMapBuilder (GEN-424, GEN-587 )
genjax-community/genjax pull request #1392
Opened 2024-10-08 19:22 UTC by sritchie

This PR:

- replaces remaining `PRNGKey` uses with `jax.random.key`
- adds `:` support to `ChoiceMap`, both in the `C[:, "x", :]` builder notation and in lookups, like `chm[:, "x", :]`
- adds a validation for making sure that users don't provide invalid selection sequences.

The validation applies to the address supplied in `ChoiceMap` creation via `C[<address>]`, and selection via `chm[<address>]`.

The rules are, after filtering out string addresses:
- you are allowed any number of `int` or `ScalarInt` address components, because drop a dimension at each `get_submap` call.
- afterward, you are allowed a single non-scalar array. (On lookup, this single entry could also be a partial slice, like `1:3`)
- the tail of the address must be all full slices, i.e. `:`

that is not FULL slice support, but it's pretty general and should help our users figure out how to create 2d slices!

```python
C[:, "x", :].set(<2d array>)
```

2024-10-09 00:17 UTC, sritchie commented on src/genjax/_src/core/generative/choice_map.py
> +                # TODO PUT THE MASK BACK ON!!!
I don't think we need to do this, actually, more soon

2024-10-14 20:13 UTC, sritchie commented on notebooks/cookbook/basics/choicemap_creation_selection.ipynb
> +    "# TODO this is broken, since we need to set a proper matrix at the bottom.\n",
@MathieuHuot , thoughts here?

2024-10-15 01:25 UTC, MathieuHuot commented on notebooks/cookbook/basics/choicemap_creation_selection.ipynb
> +    "# TODO this is broken, since we need to set a proper matrix at the bottom.\n",
@sritchie did you fix the lines right below that are right above the lines you're commenting about:
```
chm = chm ^ C[1, 3, "new_pixel"].set(1.0)  # seemingly adding a new constraint
tr, w = jax.jit(sample_image.importance)(key, chm, (image,))
w  # Yet we obtain the same weight as before
```
which were there to illustrate "But because of the nested `vmap`, the address hierarchy can sometimes lead to unintuitive results."
If so, then I suggest we remove these 2 examples showing that choicemaps for `vmap` are busted as it won't be true anymore :).

2024-10-15 01:27 UTC, MathieuHuot requested changes
Looks great overall, after you answer my comment we can merge and onto the next one!

2024-10-15 03:22 UTC, MathieuHuot approved these changes

2024-10-15 03:53 UTC, merged