(6 / N) Add `Rejuvenate` -- a proposal-driven regeneration `EditRequest`
genjax-community/genjax pull request #1411
Opened 2024-10-19 20:51 UTC by femtomc

This is an `EditRequest` whose logic follows custom proposal Metropolis-Hastings. The weight is the custom proposal Metropolis-Hastings accept reject ratio.

2024-10-20 17:39 UTC, femtomc commented on src/genjax/_src/core/generative/requests.py
> +    """
The logic here is the same as: https://github.com/probcomp/Gen.jl/blob/a5fc8e39e056acc2edd583ca6bcaa9ba1a95bde4/src/inference/mh.jl#L39-L60

2024-10-20 17:39 UTC, femtomc commented on src/genjax/_src/generative_functions/static.py
Cleaning up some naming, no change to functionality.

2024-10-20 17:40 UTC, femtomc commented on tests/inference/test_requests.py
> +        assert w == 0.0
Here's a math correctness change (change in target should be exactly the same as the inverted proposal ratio -- therefore weight is 0).

2024-10-20 17:40 UTC, femtomc commented on tests/inference/test_requests.py
> +        assert tr.get_choices()["y1"] == pytest.approx(3.0, 5e-3)
Here's a convergence check for using `Wiggle` to drive a Metropolis-Hastings move.

2024-10-21 03:26 UTC, MathieuHuot commented on src/genjax/_src/core/generative/requests.py
> +        else:
why do we need the added logic?

2024-10-21 03:54 UTC, MathieuHuot requested changes
Looks good overall. Apart from my comments above the main thing to change is the name `Wiggle`. What about calling it `Regenerate`? 
Can we unify so that Regenerate with no proposal uses the default internal one (called Regenerate in Gen.jl) and otherwise this one?

2024-10-21 03:54 UTC, MathieuHuot commented on src/genjax/_src/core/generative/requests.py
> +    """
Can we make the docstring look more like the one in Gen.jl? 
Ideally we should define a norm for technical docstrings and be consistent. Something like:
- args
- one sentence explaining technically what it is. 
- conditions of applicability
- optionally, a running example using the thing

2024-10-21 03:54 UTC, MathieuHuot commented on tests/inference/test_requests.py
> +                lambda chm: (chm.get_value(), 0.3),
is `lambda chm: (chm.get_value(), 0.3)` the argument_mapping? what does it do?

2024-10-21 03:54 UTC, MathieuHuot commented on tests/inference/test_requests.py
> +                lambda chm: (chm.get_value(), 0.3),
Am I correct to understand this is using the proposal `normal(3.0, 0.3)` here?

2024-10-21 11:29 UTC, femtomc commented
> Looks good overall. Apart from my comments above the main thing to change is the name Wiggle. What about calling it Regenerate?
Can we unify so that Regenerate with no proposal uses the default internal one (called Regenerate in Gen.jl) and otherwise this one?

How about just `Rejuvenate`?

2024-10-21 12:17 UTC, femtomc commented on src/genjax/_src/core/generative/requests.py
> +        else:
If the arguments have changed, the fallback behavior of an `EmptyRequest()` should be that we need to re-evaluate the density (which we can access via `Update(...)`)

2024-10-21 12:20 UTC, femtomc commented on tests/inference/test_requests.py
> +                lambda chm: (chm.get_value(), 0.3),
That's correct, it is the argument mapping -- it's designed to support a limited form of "introspect on local choices" functionality for the proposal (the user gets to provide a generative function as the proposal, and the argument mapping allows the generative function to introspect on the choice _at the subtrace_ which the proposal is proposing to change).

The proposal is not `normal(3.0, 0.3)` -- it's `normal(prev_value, 0.3)`.

If one wanted to do a data-driven proposal using this request, they would have to provide _a larger generative function_ (encapsulating a bigger part of the address hierarchy) to introspect on the data address.

2024-10-21 12:50 UTC, MathieuHuot commented on src/genjax/_src/core/generative/requests.py
> +        else:
I don't understand. What is the spec for an `EmptyRequest` and when does it show up? Why do we need something else than `update`?

2024-10-21 13:19 UTC, MathieuHuot commented on tests/inference/test_requests.py
> +                lambda chm: (chm.get_value(), 0.3),
ok got it! Could you just remove the "# Do some data-driven behavior" comment then as you're not doing anything data-driven here?

2024-10-21 13:21 UTC, MathieuHuot commented
> > Looks good overall. Apart from my comments above the main thing to change is the name Wiggle. What about calling it Regenerate?
> > Can we unify so that Regenerate with no proposal uses the default internal one (called Regenerate in Gen.jl) and otherwise this one?
> 
> How about just `Rejuvenate`?

sounds good!

2024-10-21 13:55 UTC, MathieuHuot commented on src/genjax/_src/core/generative/requests.py
> +    """
@femtomc can you add that this `Rejuvenate` uses the same proposal `q` for the K and for the L kernels when seen as an SMCP3 move?

2024-10-21 14:11 UTC, femtomc commented on src/genjax/_src/core/generative/requests.py
> +        else:
Without thinking, the viewpoint on `EmptyRequest()` is that it shouldn't change anything -- but strictly speaking, that's only valid _if the arguments haven't changed_ (otherwise, you can't return a weight of 0.0). We can choose to either throw and error, or ... just do the right thing, by using `Update(ChoiceMap.empty())`

There's some parts of the implementation which use `EmptyRequest()` instead of `Update(ChoiceMap.empty())` -- I think these types should behave identically, but the latter is more verbose.

We have plenty of requests which use the logic from other requests, that's nothing new.

2024-10-21 14:23 UTC, femtomc commented on src/genjax/_src/core/generative/requests.py
> +    """
I agree with the docstring suggestion, but not sure I have time to make it really nice right now.

This one:
> 
    args
    one sentence explaining technically what it is.
    conditions of applicability
    optionally, a running example using the thing

2024-10-21 14:27 UTC, MathieuHuot commented on src/genjax/_src/core/generative/requests.py
> +    """
ok good for this PR. We'll revisit docstring another time.

2024-10-21 14:27 UTC, MathieuHuot approved these changes

2024-10-21 14:32 UTC, merged