Add basic msgpack serialization
genjax-community/genjax pull request #974
Opened 2024-03-04 18:05 UTC by limarta

This provides serialization using the MsgPack backend. The implementation largely stems from[ flax's implementation](https://flax.readthedocs.io/en/latest/_modules/flax/serialization.html#msgpack_serialize).

- Supports static and combinator traces and Jax tensors.

Usage:

```python
@genjax.static_gen_fn
def model(a, b):
    p = genjax.beta(a,b) @ "p"
    v = genjax.flip(p) @ "v"
    b = genjax.bernoulli(0.25) @ "b"
    return v
key = jax.random.PRNGKey(314159)
tr = model.simulate(key, (jnp.array([0.1, 0.1, 0.1]), 0.5))

payload = msgpack_serialize.serialize(tr)
retrieved_tr = msgpack_serialize.deserialize(payload, model)
```

2024-03-04 19:17 UTC, sritchie commented on src/genjax/_src/core/serialization/msgpack.py
> +
Please add class docs, method docs, also this needs tests.

2024-03-04 19:21 UTC, sritchie requested changes
@limarta :

- needs tests
- handle the TODO
- class and method docs, please
- add a tutorial notebook showing how to perform serialization

@femtomc where else should we add docs for this new feature?

2024-03-04 19:21 UTC, sritchie commented on pyproject.toml
> +msgpack = "^1.0.7"
is there some way @limarta to make this an optional dependency? These are called "provided dependencies" in other systems... @femtomc do you have thoughts on a dep like this? should we have an extras group, so someone can do `genjax[serializable]`?

2024-03-05 14:51 UTC, limarta commented on pyproject.toml
> +msgpack = "^1.0.7"
The same can be said for `dill` which is also in the toml. Also would the import statements look a bit different if `msgpack` was an extra?

2024-03-05 16:33 UTC, femtomc commented on pyproject.toml
> +msgpack = "^1.0.7"
I think we should also remove `dill`, as Sam suggested.

2024-03-05 16:34 UTC, femtomc commented
Re -- this is awesome @limarta! Thanks for taking the first steps on serialization for GenJAX.

2024-03-05 16:35 UTC, femtomc commented
> @femtomc where else should we add docs for this new feature?

We should also add a new documentation page under `core/serialization.md` that documents (a) the serialization interfaces and (b) the supported backends.

2024-03-05 16:36 UTC, femtomc commented on pyproject.toml
> +msgpack = "^1.0.7"
@sritchie Have we figured out how to do extras groups yet?

2024-03-05 16:46 UTC, sritchie commented on pyproject.toml
> +msgpack = "^1.0.7"
This is the way to do it: https://python-poetry.org/docs/pyproject/#extras

It's not possible with poetry to do what jax does for its `cuda11` and `cuda12` extras because poetry won't let you include different clashing versions of the same-name-different-version dependency in two extras...

but we don't have that problem here!

2024-03-27 16:36 UTC, sritchie commented
@limarta can you add the new tutorial to the quarto.yml file? After that this looks good!

2024-04-11 18:26 UTC, sritchie requested changes
Few notes!

2024-04-11 18:26 UTC, sritchie commented on pyproject.toml
> -version = "0.0.1"
@limarta can you revert this? we want this version to stay inconsequential (it could even be 0.0.0) and let the dynamic versioning assign it when requested. 

And once we merge this the version will change and render this inaccurate, since it's git-sha-based)

2024-04-11 18:26 UTC, sritchie commented on pyproject.toml
> +msgpack = {version = "^1.0.8", optional = true}
remove this since you already have it below in dev right?

2024-04-11 18:26 UTC, sritchie commented on noxfile.py
>      )
let's revert this file, no need for the no-op change

2024-04-11 18:26 UTC, sritchie commented on notebooks/introduction/intro_to_genjax.ipynb
> +   "version": "3.11.8"
can you revert all of these changes? I wish this version wasn't baked in but let's keep the PR smaller

2024-04-11 18:26 UTC, sritchie commented on docs/library/index.md
> +The `genjax` package consists of several modules, many of which rely on functionality from the `genjax.core` module, and build upon the datatypes, transformation interpreters, and generative datatype
what happened without these changes?

2024-04-11 18:26 UTC, sritchie commented on pyproject.toml
> +enable = false
re-enable this, please! All of our release tooling depends on this. Is there some reason you had to turn it off?

2024-04-11 18:26 UTC, sritchie commented on src/genjax/_src/core/serialization/backend.py
> +"""This module contains a trace serialization interface that interacts with different backend implementations. Pickle or MsgPack may be used as a backend."""
I don't see how to switch between the backends. Can you show how to switch between these modes in the doc?

2024-04-15 16:43 UTC, limarta commented on src/genjax/_src/core/serialization/backend.py
> +"""This module contains a trace serialization interface that interacts with different backend implementations. Pickle or MsgPack may be used as a backend."""
Right now the backends are exposed as two separate classes. I will update the docs to show this. Later we can let users set a flag.

2024-04-16 16:39 UTC, merged